### ISSUE TITLE
Migrate to s3 + lambda

### ISSUE THREAD

**Issue by andreifilip123** [andreifilip123/t3-upgrade-web#6]
Currently, generating the diffs only works locally (it times out on Vercel) and whenever a new version appears, a lot of diffs need to be generated. This takes a lot of time to do locally and takes a good while.
I'm considering migrating this to lambda functions. 
The generateDiff function should get a new param named `isLocal = false` and based on that create everything locally or in s3/lambda/etc (I don't know anything about running on lambda currently so this may sound really stupid)

**Comment by Zeko369** [comment]
Would ISRing this with a huge stale cache time work, since this can be done on demand?

The only problem here is that it's gonna get invalidated on every deploy... there should be ways around it tho 🤔

I mean S3 would fix the problem but my point is more of a "could it be done on demand and cached by vercel instead of needed a third party provider"

**Comment by Zeko369** [comment]
#8 also isn't needed if you do it on demand

**Comment by andreifilip123** [comment]
I'm still learning about NextJS's caching ways. 
Lambda was my solution to on-demand since I couldn't get diff generation working on vercel. (That obviously would be the ideal way).
If you find any solution to doing it on Vercel that would be ideal !

**Comment by Zeko369** [comment]
I was thinking not generating anything on build and having ISR functions that on first invocation generate the diff and cache it for the next requests (i.e. caching of 1year or something, since I'm pretty sure you can't turn of the "bust cache on redeploy")

So your deploys will be lightning fast but after a deploy the first user opening the page will wait for the diff to generate (or you could do them in the build step and try to ISR new versions after the fact)

**Comment by PiotrekPKP** [comment]
> #8 also isn't needed if you do it on demand

I actually think that generating it using a webhook would be a better option - user would not need to wait for the diffs to be generated and they would always be in sync the second a new release is created. If we'd manage to get the webhook set up I'd be down to write the generator :)

**Comment by andreifilip123** [comment]
I'm okay with both @Zeko369's solution and @PiotrekPKP. The one with webhook is also something I considered and I think it could work. The only thing I dislike is that because of ISR, the build is gonna get slower and slower the more diffs we add to the repo. Generating on the fly + long cache sounds good but it would be even nicer if we could warm up the cache somehow

**Comment by andreifilip123** [comment]
I think we can start with the webhook solution for now even tho it's not super optimal and then figure out the on-demand solution and improve then. What do you think?

**Comment by PiotrekPKP** [comment]
We'd have to get approval from t3 oss team and get them to set up the webhook

**Comment by PiotrekPKP** [comment]
Oh, you've already asked them haha

**Comment by andreifilip123** [comment]
Yep. If you have any suggestions on the URL, I'm all ears 😆

**Comment by PiotrekPKP** [comment]
I think that unless we have this app in the t3 repo using https://upgrade-t3-app.vercel.app/api/webhook would be just fine. No need to over complicate that :D

**Comment by andreifilip123** [comment]
We'll get there eventually 😄

**Comment by PiotrekPKP** [comment]
> We'll get there eventually smile

I hope so! :)

**Comment by andreifilip123** [comment]
@Zeko369 we have the webhook done but it still needs to build diffs on demand. Do you still want to look into this ?

**Comment by andreifilip123** [comment]
This isn't necessary anymore. I migrated the app to SSR and fetching the diffs from the repo. That should do the job for now.
